### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by BazhinaJuliannaaa** [BazhinaJuliannaaa/course_Bazhina#1]

**Comment by BazhinaJuliannaaa** [comment]
1.Техническое задание

1.1	Общие сведения
1.1.1	Наименование
Веб – приложение «События моего города».
1.1.2	Исполнитель
Исполнителем проекта является студентка КФ МГТУ им. Н. Э. Баумана, факультета ИУК «Информатика и управление», кафедры ИУК5 «Системы обработки информации», группы ИУК5-41Б, Бажина Ю.С.
1.1.3	Плановые сроки начала и окончания работы, по созданию системы
Плановые сроки:
	Начало работы: 01.09.2023;
	Окончание работы: 31.12.2023.	

1.2	Назначение и цели создания (развития) системы
1.2.1	Назначение системы
Разрабатываемся система представляет из себя онлайн приложение, в котором будут отображаться все мероприятия для молодежи в городе Калуга. О каждом мероприятии можно будет посмотреть краткую информацию этого мероприятия, а также время и место его проведения. 
1.2.2	Цель создания системы
Система создается с целью упрощения поиска мест проведения своего досуга.
1.3	Характеристики объекта автоматизации
Объектом автоматизации является процесс поиска информации, а именно – поиск места, где можно интересно провести свой досуг

1.4	Требования к системе
1.4.1	Требования к задачам, подлежащим решению
•	Исследование и описание предметной области

1.4.2	Требования к архитектуре системы
•	Тестируемость (возможность установления факта правильного функционирования)
•	Простота обслуживания и эксплуатации 
•	Защищенность
•	Экономичность
•	Модифицируемость 
•	Функциональная расширяемость 
1.5	Состав и содержание работ по созданию системы
1.5.1	Этапы работ
•	1 этап (2 неделя). Утверждение темы, задания на разработку, технического задания (альфа);
•	2 этап (4 неделя). 25% готовности. Оформление ТЗ. Описание предметной области и требований к системе. Аналоги. Концептуальная схема. Прототип или скетчи интерфейса;
•	3 этап (7 неделя). 50% готовности. Оформление введения и исследовательской части. Обоснование выбора БД (если необходимо), логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД;
•	4 этап (10 неделя). 75% готовности. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации; 
•	5 этап (14 неделя). 100% готовности. Все ошибки и проблемы устранены.
Дополнительные условия: 
Результаты работ в течение их выполнения размещаются на сервисе GitHub, где преподаватель имеет возможность контролировать процесс выполнения работ.
Ссылка на ресурс https://github.com/BazhinaJuliannaaa/course_Bazhina
1.6	Порядок контроля и приемки системы
Установить контроль и приемку результатов работ на каждой стадии создания в соответствии с пунктом 1.5.
По окончании работы предъявляется расчетно-пояснительная записка, в состав которой входят:
•	Техническое задание;
•	Исследовательская часть;
•	Проектно-конструкторская часть;
1.7	Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
•	Настройка сервера для обеспечения безопасности и корректности функционирования системы
•	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.
1.8	 Требования к документированию
Разработку системы требуется сопровождать расчетно-пояснительной запиской и графической частью. Расчетно-пояснительная записка состоит из следующих частей:
•	Техническое задание;
•	Исследовательская часть;
•	Проектно-конструкторская часть;
•	Проектно-технологическая часть.

1.9 Источники разработки
В настоящем документе использованы следующая литература и нормативные документы:
•	ГОСТ 34.602-89 «Комплекс стандартов на автоматизированные системы. Техническое задание на создание автоматизированной системы».

**Comment by BazhinaJuliannaaa** [comment]
Техническое задание

1.	Общие сведения
    1.1	Наименование
    Интернет-магазин художественных товаров
    1.2	Исполнитель
    Исполнителем проекта является студентка КФ МГТУ им. Н. Э. Баумана, факультета ИУК «Информатика и управление», кафедры ИУК5 «Системы обработки информации», группы ИУК5-41Б, Бажина Ю.С.
    1.3	Плановые сроки начала и окончания работы, по созданию системы
    Плановые сроки:
	    Начало работы: 01.09.2023;
	    Окончание работы: 31.12.2023.	

2.	Назначение и цели создания (развития) системы
    2.1	Назначение системы
    Разрабатываемая система предоставляет пользователям возможность приобретать художественные товары из своего дома/офиса. 
    2.2	Цель создания системы
    Сервис позволяет искать, выбирать и приобретать товары в любое время и в любом месте, где есть интернет.
3.	Характеристики объекта автоматизации
        Объектом автоматизации является процесс покупки/продажи товаров для людей, которые интересуются изобразительным искусством.
4.	Требования к системе
  4.1	Требования к системе в целом
    •	Интуитивно понятый интерфейс
    •	Клиент-серверная архитектура приложения
  
  4.2	Требования к архитектуре системы
    •	Тестируемость (возможность установления факта правильного функционирования)
    •	Простота обслуживания и эксплуатации 
    •	Защищенность
    •	Экономичность
    •	Модифицируемость 
    •	Функциональная расширяемость
  4.3	Требования к основному функционалу системы 
    •	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
    •	Добавление товаров в корзину и оформление покупки
    •	Возможность оформления доставки
    •	Механизм добавления отзывов о товаре
    •	Личный кабинет покупателя
5.	Состав и содержание работ по созданию системы
  5.1	Этапы работ
        •	1 этап (2 неделя). Утверждение темы, задания на разработку, технического задания (альфа);
        •	2 этап (4 неделя). 25% готовности. Оформление ТЗ. Описание предметной области и требований к системе. Аналоги. Концептуальная схема. Прототип или скетчи интерфейса;
        •	3 этап (7 неделя). 50% готовности. Оформление введения и исследовательской части. Обоснование выбора БД (если необходимо), логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД;
        •	4 этап (10 неделя). 75% готовности. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации; 
        •	5 этап (14 неделя). 100% готовности. Все ошибки и проблемы устранены.
    Дополнительные условия: 
    Результаты работ в течение их выполнения размещаются на сервисе GitHub, где преподаватель имеет возможность контролировать процесс выполнения работ.
    Ссылка на ресурс https://github.com/BazhinaJuliannaaa/course_Bazhina
6.	Порядок контроля и приемки системы
    Установить контроль и приемку результатов работ на каждой стадии создания в соответствии с пунктом 1.5.
    По окончании работы предъявляется расчетно-пояснительная записка, в состав которой входят:
    •	Техническое задание;
    •	Исследовательская часть;
    •	Проектно-конструкторская часть;
7.	Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
    •	Настройка сервера для обеспечения безопасности и корректности функционирования системы
    •	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.
8.	 Требования к документированию
    Разработку системы требуется сопровождать расчетно-пояснительной запиской и графической частью. Расчетно-пояснительная записка состоит из следующих частей:
    •	Техническое задание;
    •	Исследовательская часть;
    •	Проектно-конструкторская часть;
    •	Проектно-технологическая часть.

9.	 Источники разработки
    В настоящем документе использованы следующая литература и нормативные документы:
    •	ГОСТ 34.602-89 «Комплекс стандартов на автоматизированные системы. Техническое задание на создание автоматизированной системы».

**Comment by wldmr-key** [comment]
тебе платят не пользователи
система предназначена для художественных магазинов, которые ведут онлайн-продажи
цель - продавать побольше ))

функции со стороны клиента - ок, единственный вопрос - что ты понимаешь под личным кабинетом? Наличие таблички "Личный кабинет" не делает ее полежной функцией?

А, вот, как насчет функций магазина? Как в систему попадают описания и категоризация товаров? как обрабатываются заказы и доставка? магазин имеет бесконечный склад?

**Comment by BazhinaJuliannaaa** [comment]
1.	Общие сведения
1.1	Наименование
        Интернет-магазин художественных товаров
1.2	Исполнитель
      Исполнителем проекта является студентка КФ МГТУ им. Н. Э. Баумана, факультета ИУК «Информатика и управление», кафедры ИУК5 «Системы обработки информации», группы ИУК5-51Б, Бажина Ю.С.
1.3	Плановые сроки начала и окончания работы, по созданию системы
        Плановые сроки:
	        Начало работы: 01.09.2023;
	        Окончание работы: 31.12.2023.	

2.	Назначение и цели создания (развития) системы
2.1	Назначение системы
        Разрабатываемая система предназначена для художественных компаний, которые ведут продажу своего товара
2.2	Цель создания системы
        Сервис позволяет увеличивать продажи производителей художественного инвентаря .
3	Характеристики объекта автоматизации
        Объектом автоматизации является процесс покупки/продажи художественных товаров.
4	Требования к системе
4.1	Требования к системе в целом
        •	Интуитивно понятый интерфейс
        •	Клиент-серверная архитектура приложения

4.2	Требования к архитектуре системы
        •	Тестируемость (возможность установления факта правильного функционирования)
        •	Простота обслуживания и эксплуатации 
        •	Защищенность
        •	Экономичность
        •	Модифицируемость 
        •	Функциональная расширяемость
4.3	Требования к основному функционалу системы 
        •	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
        •	Добавление товаров в корзину и оформление покупки
        •	Возможность оформления доставки
        •	Механизм добавления отзывов о товаре
        •	Возможность авторизации пользователя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
        •	Информация о наличии товаров на складе приходит из сторонней системы
        •	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
        •	Доставка имеет несколько состояний:
                   1. В сборке
                  2. Отправлен
                  3. Готов к получению



5	Состав и содержание работ по созданию системы
5.1	Этапы работ
        •	1 этап (2 неделя). Утверждение темы, задания на разработку, технического задания (альфа);
        •	2 этап (4 неделя). 25% готовности. Оформление ТЗ. Описание предметной области и требований к системе. Аналоги. Концептуальная схема. Прототип или скетчи интерфейса;
        •	3 этап (7 неделя). 50% готовности. Оформление введения и исследовательской части. Обоснование выбора БД (если необходимо), логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД;
        •	4 этап (10 неделя). 75% готовности. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации; 
        •	5 этап (14 неделя). 100% готовности. Все ошибки и проблемы устранены.
        Дополнительные условия: 
        Результаты работ в течение их выполнения размещаются на сервисе GitHub, где преподаватель имеет возможность контролировать процесс выполнения работ.
        Ссылка на ресурс https://github.com/BazhinaJuliannaaa/course_Bazhina
6	Порядок контроля и приемки системы
        Установить контроль и приемку результатов работ на каждой стадии создания в соответствии с пунктом 1.5.
        По окончании работы предъявляется расчетно-пояснительная записка, в состав которой входят:
        •	Техническое задание;
        •	Исследовательская часть;
        •	Проектно-конструкторская часть;
7	Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
        •	Настройка сервера для обеспечения безопасности и корректности функционирования системы
        •	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.
8	 Требования к документированию
        Разработку системы требуется сопровождать расчетно-пояснительной запиской и графической частью. Расчетно-пояснительная записка состоит из следующих частей:
        •	Техническое задание;
        •	Исследовательская часть;
        •	Проектно-конструкторская часть;
        •	Проектно-технологическая часть.

9	 Источники разработки
        В настоящем документе использованы следующая литература и нормативные документы:
        •	ГОСТ 34.602-89 «Комплекс стандартов на автоматизированные системы. Техническое задание на создание автоматизированной системы».


//Вопрос как в систему попадают описания товаров и категории все еще не закрыт. Если указать, что карточки товаров самостоятельно заполняют поставщики, это слишком глупо будет? Если нет, то вопрос по категориям. Если их изначально определить, а поставщик при загрузке своего товара будет выбирать к какой категории он относится. Таким образом можно будет исключить ситуации, что будут похожие категории, например: "Сухой материал", "сухой материал", "Сухие материалы", т.к. у каждого поставщика категория может быть записана по-своему

**Comment by wldmr-key** [comment]
> Вопрос как в систему попадают описания товаров и категории все еще не закрыт. Если указать, что карточки товаров самостоятельно заполняют поставщики, это слишком глупо будет? Если нет, то вопрос по категориям. Если их изначально определить, а поставщик при загрузке своего товара будет выбирать к какой категории он относится. Таким образом можно будет исключить ситуации, что будут похожие категории, например: "Сухой материал", "сухой материал", "Сухие материалы", т.к. у каждого поставщика категория может быть записана по-своему

это не будет глупо, это будет умно. Ты делаешь интерфейс не только для клиентов магазина, но и для поставщиков (если подумать над этим поглубже, то можно сделать это разными способами - и через формы, и через сервис (кстати через этот же сервис можно делать и складские справки, и оплаты и логистику) - это будут еще одно (или не одно) функциональное требование

Про категории ты права - это прерогатива системы (и еще одна функция - ведение категорий)

Если ты говоришь об увеличении продаж, то, интересно, они где-нибудь у тебя считаются? ))

**Comment by BazhinaJuliannaaa** [comment]
1.	Общие сведения
1.1	Наименование
Интернет-магазин художественных товаров

1.2	Исполнитель
Исполнителем проекта является студентка КФ МГТУ им. Н. Э. Баумана, факультета ИУК «Информатика и управление», кафедры ИУК5 «Системы обработки информации», группы ИУК5-51Б, Бажина Ю.С.

1.3	Плановые сроки начала и окончания работы, по созданию системы
Плановые сроки:
	Начало работы: 01.09.2023;
	Окончание работы: 31.12.2023.	

2.	Назначение и цели создания (развития) системы
2.1	Назначение системы
Разрабатываемая система предназначена для художественных компаний, которые ведут продажу своего товара

2.2	Цель создания системы
Сервис позволяет увеличивать прибыль от продажи производителей художественного инвентаря .

3	Характеристики объекта автоматизации
Объектом автоматизации является процесс покупки/продажи художественных товаров.

4	Требования к системе
4.1	Требования к системе в целом
•	Интуитивно понятый интерфейс
•	Клиент-серверная архитектура приложения

4.2	Требования к архитектуре системы
•	Тестируемость (возможность установления факта правильного функционирования)
•	Простота обслуживания и эксплуатации 
•	Защищенность
•	Экономичность
•	Модифицируемость 
•	Функциональная расширяемость

4.3	Требования к основному функционалу системы 
•	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
•	Добавление товаров в корзину и оформление покупки
•	Возможность оформления доставки
•	Механизм добавления отзывов о товаре
•	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
•	Информация о наличии товаров на складе приходит из сторонней системы
•	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
•	Доставка имеет несколько состояний:
 1. В сборке
2. Отправлен
3. Готов к получению
•	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров
•	Карточки товаров заполняет сам поставщик
•	Категории товаров – предопределенный набор данных

5	Состав и содержание работ по созданию системы
5.1	Этапы работ
•	1 этап (2 неделя). Утверждение темы, задания на разработку, технического задания (альфа);
•	2 этап (4 неделя). 25% готовности. Оформление ТЗ. Описание предметной области и требований к системе. Аналоги. Концептуальная схема. Прототип или скетчи интерфейса;
•	3 этап (7 неделя). 50% готовности. Оформление введения и исследовательской части. Обоснование выбора БД (если необходимо), логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД;
•	4 этап (10 неделя). 75% готовности. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации; 
•	5 этап (14 неделя). 100% готовности. Все ошибки и проблемы устранены.
Дополнительные условия: 
Результаты работ в течение их выполнения размещаются на сервисе GitHub, где преподаватель имеет возможность контролировать процесс выполнения работ.
Ссылка на ресурс https://github.com/BazhinaJuliannaaa/course_Bazhina

6	Порядок контроля и приемки системы
Установить контроль и приемку результатов работ на каждой стадии создания в соответствии с пунктом 1.5.
По окончании работы предъявляется расчетно-пояснительная записка, в состав которой входят:
•	Техническое задание;
•	Исследовательская часть;
•	Проектно-конструкторская часть;

7	Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
•	Настройка сервера для обеспечения безопасности и корректности функционирования системы
•	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.

8	 Требования к документированию
Разработку системы требуется сопровождать расчетно-пояснительной запиской и графической частью. Расчетно-пояснительная записка состоит из следующих частей:
•	Техническое задание;
•	Исследовательская часть;
•	Проектно-конструкторская часть;
•	Проектно-технологическая часть.

9	 Источники разработки
В настоящем документе использованы следующая литература и нормативные документы:
•	ГОСТ 34.602-89 «Комплекс стандартов на автоматизированные системы. Техническое задание на создание автоматизированной системы».



//совсем немного изменила формулировку цели создания системы (на мой взгляд так она звучит корректнее). Также добавила требования к функционалу, но не совсем уверена над правильностью формулировки последнего пункта

**Comment by wldmr-key** [comment]
норм

> Категории товаров – предопределенный набор данных

так делать нельзя - это антипаттерн

**Comment by BazhinaJuliannaaa** [comment]
тогда как лучше сделать? 
поставщики не должны создавать свои категории, они должны их выбирать из уже заранее готовых

**Comment by wldmr-key** [comment]
очевидно, в приложении должна быть функция поддержки актуального списка категорий

**Comment by BazhinaJuliannaaa** [comment]
Общие сведения
1.1 Наименование
Интернет-магазин художественных товаров
1.2 Исполнитель
Исполнителем проекта является студентка КФ МГТУ им. Н. Э. Баумана, факультета ИУК «Информатика и управление», кафедры ИУК5 «Системы обработки информации», группы ИУК5-51Б, Бажина Ю.С.

1.3 Плановые сроки начала и окончания работы, по созданию системы
Плановые сроки:
Начало работы: 01.09.2023;
Окончание работы: 31.12.2023.

Назначение и цели создания (развития) системы
2.1 Назначение системы
Разрабатываемая система предназначена для художественных компаний, которые ведут продажу своего товара
2.2 Цель создания системы
Сервис позволяет увеличивать прибыль от продажи производителей художественного инвентаря .

3 Характеристики объекта автоматизации
Объектом автоматизации является процесс покупки/продажи художественных товаров.

4 Требования к системе
4.1 Требования к системе в целом
• Интуитивно понятый интерфейс
• Клиент-серверная архитектура приложения

4.2 Требования к архитектуре системы
• Тестируемость (возможность установления факта правильного функционирования)
• Простота обслуживания и эксплуатации
• Защищенность
• Экономичность
• Модифицируемость
• Функциональная расширяемость

4.3 Требования к основному функционалу системы
• Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
• Добавление товаров в корзину и оформление покупки
• Возможность оформления доставки
• Механизм добавления отзывов о товаре
• Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
• Информация о наличии товаров на складе приходит из сторонней системы
• Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
• Доставка имеет несколько состояний:

В сборке
Отправлен
Готов к получению
• У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров
• Карточки товаров заполняет сам поставщик
• Поставщики выбирают категории из списка
• Поддержка актуального списка категорий

5 Состав и содержание работ по созданию системы
5.1 Этапы работ
• 1 этап (2 неделя). Утверждение темы, задания на разработку, технического задания (альфа);
• 2 этап (4 неделя). 25% готовности. Оформление ТЗ. Описание предметной области и требований к системе. Аналоги. Концептуальная схема. Прототип или скетчи интерфейса;
• 3 этап (7 неделя). 50% готовности. Оформление введения и исследовательской части. Обоснование выбора БД (если необходимо), логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД;
• 4 этап (10 неделя). 75% готовности. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации;
• 5 этап (14 неделя). 100% готовности. Все ошибки и проблемы устранены.
Дополнительные условия:
Результаты работ в течение их выполнения размещаются на сервисе GitHub, где преподаватель имеет возможность контролировать процесс выполнения работ.
Ссылка на ресурс https://github.com/BazhinaJuliannaaa/course_Bazhina

6 Порядок контроля и приемки системы
Установить контроль и приемку результатов работ на каждой стадии создания в соответствии с пунктом 1.5.
По окончании работы предъявляется расчетно-пояснительная записка, в состав которой входят:
• Техническое задание;
• Исследовательская часть;
• Проектно-конструкторская часть;

7 Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
• Настройка сервера для обеспечения безопасности и корректности функционирования системы
• Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.

8 Требования к документированию
Разработку системы требуется сопровождать расчетно-пояснительной запиской и графической частью. Расчетно-пояснительная записка состоит из следующих частей:
• Техническое задание;
• Исследовательская часть;
• Проектно-конструкторская часть;
• Проектно-технологическая часть.

9 Источники разработки
В настоящем документе использованы следующая литература и нормативные документы:
• ГОСТ 34.602-89 «Комплекс стандартов на автоматизированные системы. Техническое задание на создание автоматизированной системы».

**Comment by wldmr-key** [comment]
норм, хватит возиться с ТЗ - работать пора ))
