### ISSUE TITLE
Помогите с выбором темы.....

### ISSUE THREAD

**Issue by BazhinaJuliannaaa** [BazhinaJuliannaaa/course_Bazhina#2]
у меня есть несколько идей, но не знаю какие из них адекватные
1.  Продолжить идею с прошлого семестра (события города)
Добавить возможность регистрации пользователей как людей, которые посещают мероприятия и как людей, которые являются организаторами мероприятий.
2. Художественный онлайн - магазин 
3. Сервис психологической помощи
Онлайн-сервис для коммуникации психологов и пациентов. Также можно сделать раздел с различными психологическими тестами, со статьями о психологии
4.  Картинная онлайн - галерея
Веб сервис, где пользователи могут выкладывать свои работы, получать на них отзывы от других пользователей. Также можно сделать сборник картин известных художников. Можно сделать возможность заказать картину у художника
Пока писала, поняла, что проще будет продолжить тему прошлого семестра
Но в любом случае очень хочется услышать Ваше мнение

**Comment by wldmr-key** [comment]
все темы вполне адекватны

1. слабовато со сложностью данных и не очень эффектно. Если только не выйти за рамки, в которых ты находилась в прошлом семестре
2. пока ниачем. Тема мне не очень знакома, но у любого магазина очень нетривиальные внутренности. Мей би
3. Ох... Тут проблемы с данными - что там можеит быть кроме статики? тесты? и все?
4. боюсь эта штука не очень переносится в онлайн. Хотя для фриков, возможно, представляло бы интерес получение картин по фото, но база данных ((

я бы советовал первую или вторую

**Comment by BazhinaJuliannaaa** [comment]
- Касаемо первой темы:  
Вариантов "выхода за рамки" я особо не вижу (максимум - то, что я писала в прошлый раз)
- Касаемо второй:
На самом деле, у меня в голове аналог Озона, либо того же Яндекс Маркета, но в более упрощенном варианте и с уклоном на художественную тематику
- Касаемо третьей 
Можно сделать как онлайн-карточку пациентов (видела в одной из Калужский клиник, довольно полезная вещь). Т.е. хранить информацию о встречах с психологом, рекомендации психолога, возможность переписки психолога и пациента, информация о пациенте, информация о психологе, отзывы и оценки о психолога. Ну и тесты/статьи 
- касаемо четвертой темы
соглашусь, идея не очень

**Comment by wldmr-key** [comment]
> Касаемо третьей

это очень личная информация и, если переносить общение с психологом в онлайн, я бы остановился на телеге

**Comment by BazhinaJuliannaaa** [comment]
тогда можно без чата с психологом
или лучше остановиться на чем-то другом? События города?
или еще подумать над возможными темами?

**Comment by BazhinaJuliannaaa** [comment]
может электронный дневник?........
либо продолжить развивать идею о магазине.... 
я уже не знаю что можно придумать

**Comment by wldmr-key** [comment]
> может электронный дневник?........ либо продолжить развивать идею о магазине.... я уже не знаю что можно придумать

электронный дневник? школьный?  - сложновато

развивай идею о художественном магазине - ассортимент, заказы, доставка - вполне норм
