### ISSUE TITLE
Предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by BazhinaJuliannaaa** [BazhinaJuliannaaa/course_Bazhina#4]

**Comment by BazhinaJuliannaaa** [comment]
**Описание предметной области**

Онлайн-магазин художественных товаров представляет собой онлайн-платформу, специализирующуюся на продаже различных художественных продуктов и материалов для художников, хобби-художников и творческих личностей.
Для того, чтобы осуществлять торговлю необходимо 2 типа пользователей: поставщики(он же – продавец) и покупатели.
Логином пользователя считается его номер телефона, также каждому пользователю необходимо придумать пароль

**Поставщики** – пользователи, которые заинтересованы в продаже своего товара. Эти люди загружают **карточки** своих товаров, в которых содержится следующая информация:
•	Наименование товара
•	Описание товара
•	Стоимость 
•	Фотография товара
•	Количество товара на складе
Для удобства поиска товара необходимо разделять товары на **категории**. Но чтобы не было ситуаций, когда поставщики сами создают категории, которые в свою очередь могут быть очень похожими (например «Краски» и «краски»), категории должны быть отдельным списком из которого поставщики будут выбирать к какой категории отнести свой товар.
Количество товара в партии необходимо, чтобы покупатель не покупал товары, которые уже закончились. 
Поставщиков несколько, и у каждого поставщика свои карточки товаров. Также поставщик должен видеть информацию о своей выручке, а также он должен иметь возможность видеть карточки товара (например, чтобы смотреть какой товар необходимо поставить в магазин). Также при новой поставке товара поставщику нужно иметь возможность изменить информацию о количестве товара на складе. Поставщик указывает объем поставки. 

**Покупатели** – пользователи, которые приобретают товары, размещенные поставщиками. У покупателей должна быть информация о купленных ранее товарах, о товарах, которые им понравились (избранное), а также о адресе доставки. Также покупатели могут добавить отзыв о приобретенном товаре.  Покупатели собирают свой **заказ** путем его добавления в корзину, а затем оплатой самой корзины. Заказ считается оформленным, а товар купленным после оплаты корзины, также в этот момент уменьшается количество товаров на складе. 
У заказа может быть несколько состояний:
• не оформлен
• оформлен
•завершен
Статус "не оформлен" обозначает просто добавление товаров в корзину, статус "оформлен" обозначает оплату товара. После того, как заказ получит статус "оформлен", он будет передан в службу доставки. Статус "завершен" появляется после того как покупатель получит свой товар.

Один заказ – одна **доставка**. Доставку осуществляет сторонний сервис, которому мы посылаем информацию какой товар на какой адрес необходимо доставить. От службы доставки мы получаем только статус заказа, который может быть следующих видов:
•	Передан в доставку
•	В пути 
•	Получен




**Требования к системе:**
1.	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
2.	Возможность оформления доставки, которая в свою очередь реализуется сторонним сервисом
3.	Механизм добавления отзыва о товаре после покупки
4.	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
5.	Информацию о наличии товаров на складе вносит поставщик во время заполнения и редактирования карточки товара
6.	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
7.	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров, а также реализована возможность редактирования карточки товара 
8.	Карточки товаров заполняет сам поставщик
9.	Поставщики выбирают категории из списка
10.	Поддержка актуального списка категорий

//пока писала описание предметной области, поняла, что можно стоит немного изменить требования к системе

**Comment by wldmr-key** [comment]
Почувствуй разницу между описанием предметной области и требованиями к системе

Предметная область - это взаимодействие между производителем, продавцом и покупателем. Производитель производит и гарантирует поставку, продавец раскладывает по полочкам, рекламирует и гарантирует доставку, покупатель выбирает, платит и обзывается

Твоя система - автоматизирует процесс продавца. Там есть такие понятия как авторизация, права, личные кабинеты и все прочее

Постарайся это разделить в своем тексте

Кстати обрати внимание - ни одну из функций продавца ты не описала...

**Comment by BazhinaJuliannaaa** [comment]
Описание предметной области

Онлайн-магазин художественных товаров представляет собой онлайн-платформу, специализирующуюся на продаже различных художественных продуктов и материалов для художников, хобби-художников и творческих личностей.
Разрабатываемая система автоматизирует процесс продажи товаров. Для того, чтобы осуществлять торговлю необходимо 3 типа пользователей: поставщики(он же – продавец), покупатели и администраторы.

Поставщики – пользователи, которые заинтересованы в продаже своего товара.Эти люди загружают карточки своих товаров, в которых содержится следующая информация:
•	Наименование товара
•	Артикул (присваивается автоматически)
•	Описание товара
•	Стоимость 
•	Фотография товара
•	Количество товара на складе
Для удобства поиска товара, их разделяют на категории, которые в свою очередь должны быть отдельным списком, из которого поставщики будут выбирать к какой категории отнести свой товар.
Количество товара в партии необходимо, чтобы покупатель не покупал товары, которые уже закончились. 
Поставщиков несколько, и у каждого поставщика свои карточки товаров. Также поставщик должен видеть информацию о своей выручке, а также он должен иметь возможность видеть и редактировать свои карточки товара (например, чтобы при поставке новой партии товара не создавать новую карточку, а просто изменить количество товара на складе, а также будет удобно смотреть какой товар необходимо поставить в магазин). 
У поставщика есть свой личный кабинет, в котором он может видеть карточки товара и редактировать количество товара на складе, а также смотреть за выручкой от продаж своего товара. Также стоит учитывать, что сервис берет комиссию с поставщика в размере 3% от поданных товаров. 

Однако, не каждый может стать поставщиком, для этого нужно получить разрешение на продажу товара от администратора. При регистрации поставщика, администратору поступает уведомление о новом поставщике. Администратор вне системы проверяет надежность поставщика, и в зависимости от этого одобряет его или нет. Поставщик может пользоваться сервисом только после одобрения администратора. 

Покупатели – пользователи, которые приобретают товары, размещенные поставщиками.
Пользователи выбирают понравившиеся товары, добавляют их в корзину и/или в избранное.  У покупателей должна быть информация о купленных ранее товарах, а также о адресе доставки. Также покупатели могут добавить отзыв о приобретенном товаре.  Покупатели приобретают товар путем его добавления в корзину, а затем оплатой самой корзины. Товар считается купленным после оплаты корзины, также в этот момент уменьшается количество товаров на складе. 
Доставку осуществляет сторонний сервис, которому мы посылаем информацию какой товар на какой адрес необходимо доставить. От службы доставки мы получаем только статус заказа, который может быть следующих видов:
•	Передан в доставку
•	В пути 
•	Получен


Требования к системе:
1.	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
2.	Возможность оформления доставки, которая в свою очередь реализуется сторонним сервисом
3.	Механизм добавления отзыва о товаре после покупки
4.	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
5.	Информацию о наличии товаров на складе вносит поставщик во время заполнения и редактирования карточки товара
6.	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
7.	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров, а также реализована возможность редактирования карточки товара 
8.	Карточки товаров заполняет сам поставщик
9.	Поставщики выбирают категории из списка
10.	Поддержка актуального списка категорий



пока писала поняла, что у меня вопрос с доставкой. ее осуществляет сторонний сервис, получается мне его все-таки надо делать? или сказать, что информация о доставке направляется администратору, а он уже ее осуществляет/направляет информацию куда ему надо и тд? вопрос по поводу категорий. может стоит дать возможность администратору добавлять их? но если все это сделать, то в концептуальной схеме получится очень много колец.... а этого нужно избегать.....

**Comment by wldmr-key** [comment]
Повторюсь

> Почувствуй разницу между описанием предметной области и требованиями к системе
>Постарайся это разделить в своем тексте

теперь по тексту

> поставщики(он же – продавец)

старайся избегать синонимов. Они путают

> или сказать, что информация о доставке направляется администратору, а он уже ее

норм

> вопрос по поводу категорий. может стоит дать возможность администратору добавлять их?

разумеется

> но если все это сделать, то в концептуальной схеме получится очень много колец.... а этого нужно избегать.....

не тоит этого бояться, да и не получится их много

**Comment by BazhinaJuliannaaa** [comment]
Описание предметной области

Онлайн-магазин художественных товаров представляет собой онлайн-платформу, специализирующуюся на продаже различных художественных продуктов и материалов для художников, хобби-художников и творческих личностей.

Поставщик загружает свои товары на платформу, покупатель просматривает товары, добавляет понравившиеся в избранное, формирует корзину и оформляет заказ. Информация о заказе поступает администратору, который передает эту информацию другим системам. 
Разрабатываемая система автоматизирует процесс продажи товаров. Для того, чтобы осуществлять торговлю необходимо 3 типа пользователей: поставщики,покупатели и администраторы.

Поставщики – пользователи, которые заинтересованы в продаже своего товара. Эти люди загружают карточки своих товаров, в которых содержится следующая информация:
•	Наименование товара
•	Артикул (присваивается автоматически)
•	Описание товара
•	Стоимость 
•	Фотография товара
•	Количество товара на складе
Для удобства поиска товара, их разделяют на категории, которые в свою очередь должны быть отдельным списком, из которого поставщики будут выбирать к какой категории отнести свой товар.
Количество товара в партии необходимо, чтобы покупатель не покупал товары, которые уже закончились. 
Поставщиков несколько, и у каждого поставщика свои карточки товаров. Также поставщик должен видеть информацию о своей выручке, а также он должен иметь возможность видеть и редактировать свои карточки товара (например, чтобы при поставке новой партии товара не создавать новую карточку, а просто изменить количество товара на складе, а также будет удобно смотреть какой товар необходимо поставить в магазин). 
У поставщика есть свой личный кабинет, в котором он может видеть карточки товара и редактировать количество товара на складе, а также смотреть за выручкой от продаж своего товара. Также стоит учитывать, что сервис берет комиссию с поставщика в размере 3% от поданных товаров. 
Однако, не каждый может стать поставщиком, для этого нужно получить разрешение на продажу товара от администратора. При регистрации поставщика, администратору поступает уведомление о новом поставщике. Администратор вне системы проверяет надежность поставщика, и в зависимости от этого одобряет его или нет. Поставщик может пользоваться сервисом только после одобрения администратора. Администратор может добавлять новые категории товара. 

Покупатели – пользователи, которые приобретают товары, размещенные поставщиками.
Пользователи выбирают понравившиеся товары, добавляют их в корзину и/или в избранное.  У покупателей должна быть информация о купленных ранее товарах, а также о адресе доставки. Также покупатели могут добавить отзыв о приобретенном товаре.  Покупатели приобретают товар путем его добавления в корзину, а затем оплатой самой корзины. Товар считается купленным после оплаты корзины, также в этот момент уменьшается количество товаров на складе. 
Доставка осуществляется через администратора. После оформления заказа информация о нем передается администратору, который контролирует процесс доставки и изменяет статус заказа. 


Требования к системе:
1.	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
2.	Механизм добавления отзыва о товаре после покупки
3.	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
4.	Информацию о наличии товаров на складе вносит поставщик во время заполнения и редактирования карточки товара
5.	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
6.	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров, а также реализована возможность редактирования карточки товара 
7.	Карточки товаров заполняет сам поставщик
8.	Поставщики выбирают категории из списка
9.	Поддержка актуального списка категорий





> Повторюсь
> 
я не понимаю.....

**Comment by wldmr-key** [comment]
описание предметной области - это описание того, что существовало, существует и будет существовать и без твоей системы

А ты вместо этого сразу описываешь свою реализацию

**Comment by BazhinaJuliannaaa** [comment]
Описание предметной области

Все люди совершают покупки, в том числе и художники. Для приобретения необходимого товара люди приходят в магазины. Магазины бывают онлайн и оффлайн. 
Если рассматривать оффлайн магазины, то для совершения покупки человеку нужно добраться до нужного адреса, отстоять очередь, выбрать товар, оплатить его. Возникает проблема: не всегда получается быстро определиться с нужным товаром, а какие-либо заминки вызывают задержку очереди и, как следствие, негативные эмоции остальных посетителей, которые хотят поскорее приобрести необходимый им товар и пойти заниматься своими делами. Помимо покупателей, в магазинах есть люди, которые продают товар – продавцы. Эти люди помогают определиться с товаром, сканируют товары, которые покупатель приобретает, информируют об общей стоимости покупки, а также производят непосредственную продажу товара. 
Товар не берется их воздуха и не приходит самостоятельно в магазин. Его производят определенные компании, а доставкой товара до магазина занимаются поставщики. Представители магазина заключают контракты с поставщиками, которые в свою очередь доставляют партии товара в магазин. В контрактах указывается количество товара, даты поставки товара и стоимость товара, которую магазин оплачивает поставщику. 
Также есть люди, которые контролируют все процессы, которые происходят в магазине – администраторы. Они следят за количеством приобретенных покупателями товаров, смотрят за работой продавцов, следят за своевременными поставками необходимых товаров. 

Если рассматривать онлайн магазины, то тут в качестве продавца выступает сама система. Для покупки в таком магазине покупателю не нужно куда-то идти, ему нужен только доступ в интернет. Обычно на этом сервисе(магазине) покупатели регистрируются, и у них создается свой личный кабинет, в котором хранится информация о приобретенных ранее товарах. Покупатель может не спеша выбрать все необходимые товары, подробнее ознакомиться с описанием товара, посмотреть отзывы от реальных покупателей. Понравившиеся товары покупатель может отметить, как «понравившиеся» (также часто встречается слово «избранное»), либо же положить в корзину. Чтобы приобрести товар, покупатель заходит в корзину, выбирает адрес доставки своих покупок, затем оплачивает корзину. Главная цель покупателя – приобрести товар.
У поставщиков главная цель – получить прибыль с продажи товара. Но не каждый человек может стать поставщиком, для этого необходимо получить разрешение на продажу своего товара. Поставщики регистрируются на платформе, предоставляют свое разрешение на продажу товара, и ждут одобрения от администраторов магазина на продажу своего товара. Поставщики самостоятельно заполняют карточки товара, в которых содержится описание продукта, его стоимость, фотография и т.д. Затем покупатели могут просматривать заполненные карточки и совершать покупку товара, изображенного на них. 
Для удобства поиска необходимых продуктов, товары разделяют на категории. 
Контролирует работу магазина администратор. Он смотрит за выручкой магазина, который берет процент продаж с поставщиков, контролирует процесс доставки товара покупателю, одобряет либо отклоняет разрешение поставщиков на продажу товара.


Требования к системе:
1.	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
2.	Механизм добавления отзыва о товаре после покупки
3.	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
4.	Информацию о наличии товаров на складе вносит поставщик во время заполнения и редактирования карточки товара
5.	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
6.	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров, а также реализована возможность редактирования карточки товара 
7.	Карточки товаров заполняет сам поставщик
8.	Поставщики выбирают категории из списка
9.	Поддержка актуального списка категорий
Онлайн-магазин художественных товаров представляет собой онлайн-платформу, специализирующуюся на продаже различных художественных продуктов и материалов для художников, хобби-художников и творческих личностей.

Поставщик загружает свои товары на платформу, покупатель просматривает товары, добавляет понравившиеся в избранное, формирует корзину и оформляет заказ. Информация о заказе поступает администратору, который передает эту информацию другим системам. 
Разрабатываемая система автоматизирует процесс продажи товаров. Для того, чтобы осуществлять торговлю необходимо 3 типа пользователей: поставщики,покупатели и администраторы.

Поставщики – пользователи, которые заинтересованы в продаже своего товара. Эти люди загружают карточки своих товаров, в которых содержится следующая информация:
•	Наименование товара
•	Артикул (присваивается автоматически)
•	Описание товара
•	Стоимость 
•	Фотография товара
•	Количество товара на складе
Для удобства поиска товара, их разделяют на категории, которые в свою очередь должны быть отдельным списком, из которого поставщики будут выбирать к какой категории отнести свой товар.
Количество товара в партии необходимо, чтобы покупатель не покупал товары, которые уже закончились. 
Поставщиков несколько, и у каждого поставщика свои карточки товаров. Также поставщик должен видеть информацию о своей выручке, а также он должен иметь возможность видеть и редактировать свои карточки товара (например, чтобы при поставке новой партии товара не создавать новую карточку, а просто изменить количество товара на складе, а также будет удобно смотреть какой товар необходимо поставить в магазин). 
У поставщика есть свой личный кабинет, в котором он может видеть карточки товара и редактировать количество товара на складе, а также смотреть за выручкой от продаж своего товара. Также стоит учитывать, что сервис берет комиссию с поставщика в размере 3% от поданных товаров. 
Однако, не каждый может стать поставщиком, для этого нужно получить разрешение на продажу товара от администратора. При регистрации поставщика, администратору поступает уведомление о новом поставщике. Администратор вне системы проверяет надежность поставщика, и в зависимости от этого одобряет его или нет. Поставщик может пользоваться сервисом только после одобрения администратора. Администратор может добавлять новые категории товара. 

Покупатели – пользователи, которые приобретают товары, размещенные поставщиками.
Пользователи выбирают понравившиеся товары, добавляют их в корзину и/или в избранное.  У покупателей должна быть информация о купленных ранее товарах, а также о адресе доставки. Также покупатели могут добавить отзыв о приобретенном товаре.  Покупатели приобретают товар путем его добавления в корзину, а затем оплатой самой корзины. Товар считается купленным после оплаты корзины, также в этот момент уменьшается количество товаров на складе. 
Доставка осуществляется через администратора. После оформления заказа информация о нем передается администратору, который контролирует процесс доставки и изменяет статус заказа. 




Или стоит убрать большой текст с описания предметной области и оставить только список требований?

**Comment by wldmr-key** [comment]
не стоит. Стоит отредактировать текст по стилю и согласованию падежей

**Comment by BazhinaJuliannaaa** [comment]
Описание предметной области

Все люди совершают покупки, в том числе и художники. Для приобретения необходимого товара люди приходят в магазины. Магазины бывают онлайн и оффлайн. 
Если рассматривать оффлайн магазины, то для совершения покупки человеку необходимо добраться до нужного адреса, отстоять очередь, выбрать товар, оплатить его. Возникает проблема: не всегда получается быстро определиться с нужным товаром, а какие-либо заминки вызывают задержку очереди и, как следствие, негативные эмоции посетителей, которые хотят поскорее приобрести необходимый им товар и пойти по своим делам. Помимо покупателей, в магазинах есть люди, которые продают товар – продавцы. Эти люди помогают определиться с товаром, сканируют товары, которые покупатель приобретает, информируют об общей стоимости покупки, а также производят непосредственную продажу товара. 
Товар производят определенные компании, а его доставкой до магазина занимаются поставщики. Представители магазина заключают контракты с поставщиками, которые в свою очередь доставляют партии товара в магазин. В контрактах указывается количество товара, даты поставки и стоимость товара, которую магазин оплачивает поставщику. 
Также есть люди, которые контролируют все процессы, происходящие в магазине – администраторы. Они следят за количеством приобретенных покупателями товаров, смотрят за работой продавцов, следят за своевременными поставками необходимых товаров. 

Если рассматривать онлайн магазины, то тут в качестве продавца выступает система. Для покупки в таком магазине покупателю не нужно куда-то идти, нужен только доступ в интернет. Обычно на этом сервисе(магазине) покупатели регистрируются, и у них создается свой личный кабинет, в котором хранится информация о приобретенных ранее товарах. Покупатель может не спеша выбрать все необходимые товары, подробнее ознакомиться с описанием товара, посмотреть отзывы от реальных покупателей. Понравившиеся товары покупатель может отметить, как «понравившиеся» (также часто встречается слово «избранное»), либо же положить в корзину. Чтобы приобрести товар, покупатель заходит в корзину, выбирает адрес доставки своих покупок, затем оплачивает корзину. Главная цель покупателя – приобрести товар.
У поставщиков главная цель – получить прибыль с продажи товара. Но не каждый человек может стать поставщиком, для этого необходимо получить разрешение на продажу своего товара. Поставщики регистрируются на платформе, предоставляют свое разрешение на торговлю, и ждут одобрения от администраторов магазина на продажу своего товара. Поставщики самостоятельно заполняют карточки товаров, в которых содержится описание продукта, его стоимость, фотография и т.д. Затем покупатели могут просматривать заполненные карточки и совершать покупку товаров, которые изображены на них. 
Для удобства поиска необходимых продуктов, товары разделяют на категории. 
Контролирует работу магазина администратор. Он смотрит за выручкой магазина, которая берется с процента продаж товаров поставщиков. Также администратор контролирует процесс доставки товара покупателю, одобряет либо отклоняет разрешение поставщиков на продажу товара.


Требования к системе:
1.	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
2.	Механизм добавления отзыва о товаре после покупки
3.	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
4.	Информацию о наличии товаров на складе вносит поставщик во время заполнения и редактирования карточки товара
5.	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
6.	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров, а также реализована возможность редактирования карточки товара 
7.	Карточки товаров заполняет сам поставщик
8.	Поставщики выбирают категории из списка
9.	Поддержка актуального списка категорий
Онлайн-магазин художественных товаров представляет собой онлайн-платформу, специализирующуюся на продаже различных художественных продуктов и материалов для художников, хобби-художников и творческих личностей.
Поставщик загружает свои товары на платформу, покупатель просматривает товары, добавляет понравившиеся в избранное, формирует корзину и оформляет заказ. Информация о заказе поступает администратору, который передает эту информацию другим системам. 
Разрабатываемая система автоматизирует процесс продажи товаров. Для того, чтобы осуществлять торговлю необходимо 3 типа пользователей: поставщики, покупатели и администраторы.

Поставщики – пользователи, которые заинтересованы в продаже своего товара. Эти люди загружают карточки своих товаров, в которых содержится следующая информация:
•	Наименование товара
•	Артикул (присваивается автоматически)
•	Описание товара
•	Стоимость 
•	Фотография товара
•	Количество товара на складе
Для удобства поиска товара, их разделяют на категории, которые в свою очередь должны быть отдельным списком, из которого поставщики будут выбирать к какой категории отнести свой товар.
Количество товара в партии необходимо, чтобы покупатель не покупал товары, которые уже закончились. 
Поставщиков несколько, и у каждого поставщика свои карточки товаров. Также поставщик должен видеть информацию о своей выручке, а также он должен иметь возможность видеть и редактировать свои карточки товара (например, чтобы при поставке новой партии товара не создавать новую карточку, а просто изменить количество товара на складе, а также будет удобно смотреть какой товар необходимо поставить в магазин). 
У поставщика есть свой личный кабинет, в котором он может видеть карточки товара, редактировать количество товара на складе, а также смотреть за выручкой. Также стоит учитывать, что сервис берет комиссию с поставщика в размере 3% от проданных товаров. 
Однако, не каждый может стать поставщиком, для этого нужно получить разрешение на продажу товара от администратора. При регистрации поставщика, администратору поступает уведомление о новом поставщике. Администратор вне системы проверяет надежность поставщика, и в зависимости от этого одобряет его или нет. Поставщик может пользоваться сервисом только после одобрения администратора. Администратор может добавлять новые категории товара. 

Покупатели – пользователи, которые приобретают товары, размещенные поставщиками.
Пользователи выбирают понравившиеся товары, добавляют их в корзину и/или в избранное.  У покупателей должна быть информация о купленных ранее товарах, а также о адресе доставки. Также покупатели могут добавить отзыв о приобретенном товаре.  Покупатели приобретают товар путем его добавления в корзину, а затем оплатой самой корзины. Товар считается купленным после оплаты корзины, также в этот момент уменьшается количество товара на складе. 
Доставка осуществляется через администратора. После оформления заказа информация о нем передается администратору, который контролирует процесс доставки и изменяет статус заказа.

**Comment by wldmr-key** [comment]
наконец, определилась с доставкой ))

кстати, в каком месте курсовой работы ты определишь четко, сколько у заказа разных статусов? ))

а так - вполне норм

**Comment by BazhinaJuliannaaa** [comment]
> кстати, в каком месте курсовой работы ты определишь четко, сколько у заказа разных статусов? ))
> 


когда приблизилась к концу концептуальной схемы..... вроде бы..... по после этого вопроса уже не уверена....

**Comment by BazhinaJuliannaaa** [comment]
> кстати, в каком месте курсовой работы ты определишь четко, сколько у заказа разных статусов? ))

а это нужно где-то указать?

**Comment by wldmr-key** [comment]
> > кстати, в каком месте курсовой работы ты определишь четко, сколько у заказа разных статусов? ))
> 
> а это нужно где-то указать?

а ты софт писать собираешься? ))

**Comment by BazhinaJuliannaaa** [comment]
> > > кстати, в каком месте курсовой работы ты определишь четко, сколько у заказа разных статусов? ))
> > 
> > 
> > а это нужно где-то указать?
> 
> а ты софт писать собираешься? ))

ну да.....

**Comment by wldmr-key** [comment]
и как ты там собираешься обрабатывать статусы? Может, на берегу стоит договориться?

**Comment by BazhinaJuliannaaa** [comment]
Описание предметной области

Все люди совершают покупки, в том числе и художники. Для приобретения необходимого товара люди приходят в магазины. Магазины бывают онлайн и оффлайн. 
Если рассматривать оффлайн магазины, то для совершения покупки человеку необходимо добраться до нужного адреса, отстоять очередь, выбрать товар, оплатить его. Возникает проблема: не всегда получается быстро определиться с нужным товаром, а какие-либо заминки вызывают задержку очереди и, как следствие, негативные эмоции посетителей, которые хотят поскорее приобрести необходимый им товар и пойти по своим делам. Помимо покупателей, в магазинах есть люди, которые продают товар – продавцы. Эти люди помогают определиться с товаром, сканируют товары, которые покупатель приобретает, информируют об общей стоимости покупки, а также производят непосредственную продажу товара. 
Товар производят определенные компании, а его доставкой до магазина занимаются поставщики. Представители магазина заключают контракты с поставщиками, которые в свою очередь доставляют партии товара в магазин. В контрактах указывается количество товара, даты поставки и стоимость товара, которую магазин оплачивает поставщику. 
Также есть люди, которые контролируют все процессы, происходящие в магазине – администраторы. Они следят за количеством приобретенных покупателями товаров, смотрят за работой продавцов, следят за своевременными поставками необходимых товаров. 

Если рассматривать онлайн магазины, то тут в качестве продавца выступает система. Для покупки в таком магазине покупателю не нужно куда-то идти, нужен только доступ в интернет. Обычно на этом сервисе(магазине) покупатели регистрируются, и у них создается свой личный кабинет, в котором хранится информация о приобретенных ранее товарах. Покупатель может не спеша выбрать все необходимые товары, подробнее ознакомиться с описанием товара, посмотреть отзывы от реальных покупателей. Понравившиеся товары покупатель может отметить, как «понравившиеся» (также часто встречается слово «избранное»), либо же положить в корзину. Чтобы приобрести товар, покупатель заходит в корзину, выбирает адрес доставки своих покупок, затем оплачивает корзину. Главная цель покупателя – приобрести товар.
У поставщиков главная цель – получить прибыль с продажи товара. Но не каждый человек может стать поставщиком, для этого необходимо получить разрешение на продажу своего товара. Поставщики регистрируются на платформе, предоставляют свое разрешение на торговлю, и ждут одобрения от администраторов магазина на продажу своего товара. Поставщики самостоятельно заполняют карточки товаров, в которых содержится описание продукта, его стоимость, фотография и т.д. Затем покупатели могут просматривать заполненные карточки и совершать покупку товаров, которые изображены на них. 
Для удобства поиска необходимых продуктов, товары разделяют на категории. 
Контролирует работу магазина администратор. Он смотрит за выручкой магазина, которая берется с процента продаж товаров поставщиков. Также администратор контролирует процесс доставки товара покупателю, одобряет либо отклоняет разрешение поставщиков на продажу товара.


Требования к системе:
1.	Разделение товаров на категории с возможностью фильтрации и поиска по категориям и характеристикам.
2.	Механизм добавления отзыва о товаре после покупки
3.	Возможность авторизации покупателя для сохранения информации о прошлых покупках, избранных товарах, адресов доставки
4.	Информацию о наличии товаров на складе вносит поставщик во время заполнения и редактирования карточки товара
5.	Приобрести товар можно путем добавления товара в корзину, затем оплатой корзины. Покупкой товара считается завершенный процесс оплаты товаров, которые находятся в корзине.
6.	У продавцов свой личный кабинет, в котором будет учитываться выручка от продаж товаров, а также реализована возможность редактирования карточки товара 
7.	Карточки товаров заполняет сам поставщик
8.	Поставщики выбирают категории из списка
9.	Поддержка актуального списка категорий
Онлайн-магазин художественных товаров представляет собой онлайн-платформу, специализирующуюся на продаже различных художественных продуктов и материалов для художников, хобби-художников и творческих личностей.
Поставщик загружает свои товары на платформу, покупатель просматривает товары, добавляет понравившиеся в избранное, формирует корзину и оформляет заказ. Информация о заказе поступает администратору, который передает эту информацию другим системам. 
Разрабатываемая система автоматизирует процесс продажи товаров. Для того, чтобы осуществлять торговлю необходимо 3 типа пользователей: поставщики, покупатели и администраторы.

Поставщики – пользователи, которые заинтересованы в продаже своего товара. Эти люди загружают карточки своих товаров, в которых содержится следующая информация:
•	Наименование товара
•	Артикул (присваивается автоматически)
•	Описание товара
•	Стоимость 
•	Фотография товара
•	Количество товара на складе
Для удобства поиска товара, их разделяют на категории, которые в свою очередь должны быть отдельным списком, из которого поставщики будут выбирать к какой категории отнести свой товар.
Количество товара в партии необходимо, чтобы покупатель не покупал товары, которые уже закончились. 
Поставщиков несколько, и у каждого поставщика свои карточки товаров. Также поставщик должен видеть информацию о своей выручке, а также он должен иметь возможность видеть и редактировать свои карточки товара (например, чтобы при поставке новой партии товара не создавать новую карточку, а просто изменить количество товара на складе, а также будет удобно смотреть какой товар необходимо поставить в магазин). 
У поставщика есть свой личный кабинет, в котором он может видеть карточки товара, редактировать количество товара на складе, а также смотреть за выручкой. Также стоит учитывать, что сервис берет комиссию с поставщика в размере 3% от проданных товаров. 
Однако, не каждый может стать поставщиком, для этого нужно получить разрешение на продажу товара от администратора. При регистрации поставщика, администратору поступает уведомление о новом поставщике. Администратор вне системы проверяет надежность поставщика, и в зависимости от этого одобряет его или нет. Поставщик может пользоваться сервисом только после одобрения администратора. Администратор может добавлять новые категории товара. 

Покупатели – пользователи, которые приобретают товары, размещенные поставщиками.
Пользователи выбирают понравившиеся товары, добавляют их в корзину и/или в избранное.  У покупателей должна быть информация о купленных ранее товарах, а также о адресе доставки. Также покупатели могут добавить отзыв о приобретенном товаре.  Покупатели приобретают товар путем его добавления в корзину, а затем оплатой самой корзины. Товар считается купленным после оплаты корзины, также в этот момент уменьшается количество товара на складе. 
Доставка осуществляется через администратора. После оформления заказа информация о нем передается администратору, который контролирует процесс доставки и изменяет статус заказа. 
У заказа может быть один из следующих статусов:
1.	Не оформлен. В этом случае заказ находится на этапе формирования (в корзине), где пользователь добавляет или удаляет товары, которые хочет приобрести. Статус добавляется автоматически при добавлении первого товара в корзину.
2.	Оплачен. Пользователь выбрал товары и оплатил их. Статус изменяется автоматически после оплаты товара.
3.	Передан в доставку. Товар собран на складе и отправлен службе доставки. Статус заказа изменяет администратор магазина, который как раз передает информацию о заказе службе доставки. 
4.	Доставлен. Товар доставлен до получателя. Статус изменяет администратор после того, как получит информацию от службы доставки об успешном выполнении заказа.

**Comment by wldmr-key** [comment]
пойдет
