### ISSUE TITLE
Концептуальная схема данных предметной области

### ISSUE THREAD

**Issue by BazhinaJuliannaaa** [BazhinaJuliannaaa/course_Bazhina#6]

**Comment by BazhinaJuliannaaa** [comment]
![курсач drawio (1)](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/bf2bb8a4-b202-4a08-8683-6d6a6301ffab)

//я не совсем понимаю к чему относить отзывы....

**Comment by wldmr-key** [comment]
не надо такие штуки по ночам рисовать!

Заказ связывается с покупателем (правильно) и с поставщиком (ой!!!)

В заказе разве только один товар может быть?

Зачем сущность доставка со связью 1:1? Почему атрибуты доставки не могут быть в заказе?

Про отзывы ты правильно все поняла - они должны быть связаны только с заказом (правда, опять непонятно как быть, если в заказе несколько товаров)

И откуда у тебя в концептуальной схеме взялись id?! Их нет в описании предметной области!

**Comment by BazhinaJuliannaaa** [comment]
![1 (2)](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/f680ff54-284f-4ab9-bf3a-fbd56598616e)

**Comment by wldmr-key** [comment]
Обращаю внимание - часть атрибутов не описана в предметной области. Это как?

Ты рисуешь, что в заказе несколько товаров. Сколько? Как определить, что в заказе 5 одинаковых кисточек?

Избранные товары - это что? они имеют отношение к товарам? Если да, то где связь?

Корзина - аналогично

Атрибут "заказы" у покупателя - это за гранью добра и зла ))

**Comment by BazhinaJuliannaaa** [comment]
![концептуальная модель drawio](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/1d259bc2-0979-4fda-a731-8064fa1703ae)
добавила атрибут "количество" в заказах
избранное - то, что люди помечают сердечком, связь сделала
поняла, что корзина - это тот же самый заказ, но со статусом "не оформлен"
предметную область переделаю после консультации в четверг, когда пойму что делать с доставкой......
а нормально, что у меня в схеме так много колец получается?.....

**Comment by wldmr-key** [comment]
> а нормально, что у меня в схеме так много колец получается?.....

а, зачем, ты их столько сделала?

для начала разберись с заказом: там может быть несколько товаров в разных количествах - 2 кисточки, 3 краски, 4 альбома и 1 мольберт? Если да, то это не укладывается в твою схему

Зачем связывать отзыв с покупателем, если отзыв уже связан с заказом, по которому ты и так можешь найти покупателя

Самая большая печаль - зачем ты в качестве атрибутов вставляешь связи (заказ или избранное у покупателей, например) ?

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/c60a384b-4532-4ec6-8299-2002817a2ee7)

**Comment by wldmr-key** [comment]
ай, молодец! Все намного лучше стало

очевидно, некоторые неочевидные стрелки имеет смысл подписать (вроде избранного)
очевидно, стоит дополнить описание предметой области и требований к системе, чтобы появление концептуальной схемы стало логичным

стрелка между товарами в заказе и заказами неправильная

отзыв относится к заказу (такое может быть - ддоставили, допустим, плохо) или к товару (краски не радуют) - я не знаю - тебе виднее. Но в любом случае вряд ли один отзыв может быть написан на несколько заказов, как у тебя нарисовано

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/534ea3fe-7dcf-4e75-930e-c01fc56cb5b1)
отзывы должны быть на товары. Или стоит их вернуть по связям к заказам, но просто обозначить, что это отзыв на товар? 
описание предметной области и требований к системе завтра подправлю

**Comment by wldmr-key** [comment]
нет, если отзывы на товары, то так нормально
поговорим о деньгах...
стоимость товара устанавливается поставщиком и может им изменяться
сумма заказа - это сумма стоимостей товаров умноженных на их количества плюс, возможно, стоимость доставки
Таким образом, определить, допустим, сумму продаж для поставщика за месяц становится невозможно (так как цены менялись и им, и другими поставщиками)

я бы предложил ставить цену товара в "Товары в заказе", фиксируя ее для статистики

> описание предметной области и требований к системе завтра подправлю

мы же договаривались будущее время не употреблять ))

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/0a1032e4-97f9-45bd-99d8-ad34496fdeb3)
Тогда вопрос: а стоит ли оставлять сумму заказа? С одном стороны - покупатель же платит не за каждый товар отдельно, а за весь заказ в целом. А с другой - ну это же можно посчитать из "товары в заказе"

**Comment by wldmr-key** [comment]
не стоит, если на сумму не влияют другие факторы

**Comment by BazhinaJuliannaaa** [comment]
хорошо, тогда следующий вопрос
если исходить из размышлений об администраторе, для него нужна сущность или нет? или это просто человек, который следит за системой и все? 
если администратор разрешает поставщику продавать товар, то может для поставщика нужен новый атрибут по типу "разрешение"? мол если там лежит "да", то тогда поставщику можно создавать карточки товаров и тд, а если нет , то пусть просто существует. Или стоит сделать, что администратор сам создает профиль поставщика и он сразу может продавать? тогда новый атрибут не нужен

**Comment by wldmr-key** [comment]
Ты решила делать разные сущности для покупателей и поставщиков. По этой логике и для работников магазина должна быть отдельная сущность.

Про возможные функции администратора я писал выше.

> ля поставщика нужен новый атрибут по типу "разрешение"? мол если там лежит "да", то тогда поставщику можно создавать карточки товаров и тд, а если нет , то пусть просто существует

хорошо

> администратор сам создает профиль поставщика

так тоже можно, но хуже

И, чтобы два раза не вставать - что это за "выручка" осталась у поставщика? ))

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/77a8bc21-28f4-44ed-b125-0ea23e62b96b)

**Comment by wldmr-key** [comment]
"продажи магазина"... ох...
разрешение на торговлю есть, если есть связь, наверное

Я бы сказал не администратор, а сотрудники...

Сумму заказа решила оставить?

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/7ec5f40d-0742-4d0a-8b59-803a20767102)

**Comment by wldmr-key** [comment]
норм. Статус заказа и статус доставки - это не совмещается?

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/ae1d0d41-fd4d-44c3-8258-85edf60b8aa8)

**Comment by wldmr-key** [comment]
ок
