### ISSUE TITLE
Прототип/скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by BazhinaJuliannaaa** [BazhinaJuliannaaa/course_Bazhina#7]

**Comment by BazhinaJuliannaaa** [comment]
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/e84cb933-b74c-40fc-a1a6-7068cb269431)

Вход и регистрация для поставщиков и покупателей одинаковая
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/fb806f00-595f-4baf-b895-7e40c0234b74)

![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/cf914bec-b0a1-4fa2-934a-7ebf89f8ec0d)

Кабинет покупателей:
Вкладка "все товары" с возможностью поиска по имени и фильтры (в строке поиска справа кнопочка)
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/48f7d875-8861-4fab-ba14-057abf81f2ee)

Вкладка "избранное"
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/bce5db58-c356-4ccd-9f8b-9985d6084b94)

Вкладка "корзина"
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/9fa6abcc-b264-4b0f-9646-a445b6556add)

Вкладка "мои заказы". Если нажать на кнопку "детали заказа", можно посмотреть всю информацию, а также написать отзыв на приобретенный товар (но только в том случае, если у него будет статус "доставлен")
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/c5444acc-c1a0-4fbf-8043-477e745c0a70)

![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/a2902c83-1790-47af-afde-5779e85a40fd)

Кабинет поставщиков:
Вкладка "добавить карточку"
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/c7c531dc-9bfa-4e0d-8312-79c8c2877d11)

Вкладка "мои карточки". Если нажать на кнопку "изменить количество на складе", то появится окно де это можно будет сделать
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/6da0aa17-0032-4041-bf30-1425e508b386)

Вкладка "прибыль". Просто отображение общей прибыли и прибыли за последний день
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/ca28e92e-7698-4808-8fd0-d69c2e7b51a6)

**Comment by wldmr-key** [comment]
по ночам спать следует!!!

Обрати внимание - из скетчей сразу видно:

1) продавцы регистрируются совершенно безнаказанно. То есть, любой человек с улицы приходит в твой онлайн магазин и набивает его всяким хламом. В лучшем случае

2) если в твоем магазине будет 1000 товаров (а, кстати, сколько их будет?) как ты будешь выдавать

3) если у поставщика больше 20 товаров, то каждый день корректировать остатки по складу ему будет тяжело (хинт - предусмотреть веб-сервис для автоматизированной актуализации, аналогичный форме)

4) вряд ли кого интересует только сегодняшняя прибыль. Кстати прибыль ли?

5) а онлайн-магазину свои финансовые показатели неинтересны?

**Comment by BazhinaJuliannaaa** [comment]
1. для продавцов следует сделать поле ввода ИНН? ??(нужно сделать пометку, что продавцом может стать только юридическое лицо)
2. вообще не поняла этот пункт......
3. как его лучше сделать? мне помимо этой системы нужно разрабатывать еще одну? если да, то не слишком много для 2х месяцев? если не нужно разрабатывать 2ю систему(на что я очень сильно надеюсь), то что делать? вообще не понимаю как реализовать этот момент....
4. вместо прибыли написать "выручка"? или вообще убрать эту вкладку? 
5. сделать еще одну сущность по типу "администратор", где будет показана выручка сервиса(магазина) от продаж поставщиков???

**Comment by deep0r** [comment]
Второй пункт, как я понял мол, если смотреть в качестве примера ВБ, то там же много различных товаров и их продвигает система в топ, чтобы они показывались сразу на первой странице. Делает это она по разным алгоритмам. Ты также будешь это делать?

**Comment by wldmr-key** [comment]
> 1. для продавцов следует сделать поле ввода ИНН? ??(нужно сделать пометку, что продавцом может стать только юридическое лицо)

очевидно, не поможет, когда придет злодей

> 2. вообще не поняла этот пункт......

плохо выразился. Как ты их будешь показывать в своем интерфейсе? 1000 фоток?

> 3. как его лучше сделать? мне помимо этой системы нужно разрабатывать еще одну? если да, то не слишком много для 2х месяцев? если не нужно разрабатывать 2ю систему(на что я очень сильно надеюсь), то что делать? вообще не понимаю как реализовать этот момент....

веб-сервис, вообще-то, это очень простая штука. Предлагаю в качестве задачи минимум написать где-нибудь здесь или в заключении, что взаимодействовать продавцы с онлайн-магазином смогут также через веб-сервис, который ты, может быть, напишешь ))
Напомни мне на консультации, я всем расскажу

> 4. вместо прибыли написать "выручка"? или вообще убрать эту вкладку?

объем продаж или продажи, или отчет по продажам (тут можно много фантазировать). И, желательно, за любой период

> 5. сделать еще одну сущность по типу "администратор", где будет показана выручка сервиса(магазина) от продаж поставщиков???

я бы сказал - роль. Он, например, может редактировать список категорий, утверждать запросы на авторизацию поставщиков и, да, смотреть за оборотом магазина

**Comment by BazhinaJuliannaaa** [comment]
> Второй пункт, как я понял мол, если смотреть в качестве примера ВБ, то там же много различных товаров и их продвигает система в топ, чтобы они показывались сразу на первой странице. Делает это она по разным алгоритмам. Ты также будешь это делать?

я на самом деле не планировала.... это же курсовая по моделям данных, значит главная цель - именно построить модель для магазина, а не наполнить приложение всякими приколами....

**Comment by deep0r** [comment]
> > Второй пункт, как я понял мол, если смотреть в качестве примера ВБ, то там же много различных товаров и их продвигает система в топ, чтобы они показывались сразу на первой странице. Делает это она по разным алгоритмам. Ты также будешь это делать?
> 
> я на самом деле не планировала.... это же курсовая по моделям данных, значит главная цель - именно построить модель для магазина, а не наполнить приложение всякими приколами....

Как вариант, может добавить рейтинг к товарам и просто сначала выводить товары с хорошим рейтингом
Правда, возникает другой вопрос кто может ставить рейтинг. Очевидно, это не должен делать любой пользователь. Поэтому надо будет отслеживать покупал ли этот товар данный пользователь, если да, то может оценить, иначе нет.

Но это чисто мои мысли, но звучит прикольно

**Comment by BazhinaJuliannaaa** [comment]
> я бы сказал - роль. Он, например, может редактировать список категорий, утверждать запросы на авторизацию поставщиков и, да, смотреть за оборотом магазина

> очевидно, не поможет, когда придет злодей

а что тогда делать..... а если сделать как раз администратора (обозначить, что в самом начале 1 администратор магазина, но у него есть возможность создавать аккаунты для других администраторов), который как раз будет делать аккаунты для поставщиков? а проверять на сколько адекватный этот поставщик(там может какую-то документацию и тд), а также связываться с поставщиком администратор будет где-то в другом месте? Ну да, и следить за оборотом магазина

> плохо выразился. Как ты их будешь показывать в своем интерфейсе? 1000 фоток?

одна карточка товара - один вот такой элемент 
![image](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/6c5f9eab-4d2f-4fc7-bdf7-fa05511120f2)
если "кол-во на складе"==0, то не показывается товар, если >1, то показывается только одна такая карточка


> веб-сервис, вообще-то, это очень простая штука. Предлагаю в качестве задачи минимум написать где-нибудь здесь или в заключении, что взаимодействовать продавцы с онлайн-магазином смогут также через веб-сервис, который ты, может быть, напишешь )) Напомни мне на консультации, я всем расскажу

все равно ничего не поняла, жду консультацию......

> объем продаж или продажи, или отчет по продажам (тут можно много фантазировать). И, желательно, за любой период

этот момент поняла, учту

**Comment by BazhinaJuliannaaa** [comment]
> > > Второй пункт, как я понял мол, если смотреть в качестве примера ВБ, то там же много различных товаров и их продвигает система в топ, чтобы они показывались сразу на первой странице. Делает это она по разным алгоритмам. Ты также будешь это делать?
> > 
> > 
> > я на самом деле не планировала.... это же курсовая по моделям данных, значит главная цель - именно построить модель для магазина, а не наполнить приложение всякими приколами....
> 
> Как вариант, может добавить рейтинг к товарам и просто сначала выводить товары с хорошим рейтингом Правда, возникает другой вопрос кто может ставить рейтинг. Очевидно, это не должен делать любой пользователь. Поэтому надо будет отслеживать покупал ли этот товар данный пользователь, если да, то может оценить, иначе нет.
> 
> Но это чисто мои мысли, но звучит прикольно

ну исходя из описания предметной области, у меня есть такая функция, как отзывы. Отзывы покупатель может сделать только на приобретенный товар (на вб и яндексе сейчас вроде как такая же функция). Как вариант в отзыве можно добавить возможность поставить рейтинг (0-5), а при отображении элементов сделать просто сортировку по рейтингу.

**Comment by deep0r** [comment]
> > > > Второй пункт, как я понял мол, если смотреть в качестве примера ВБ, то там же много различных товаров и их продвигает система в топ, чтобы они показывались сразу на первой странице. Делает это она по разным алгоритмам. Ты также будешь это делать?
> > > 
> > > 
> > > я на самом деле не планировала.... это же курсовая по моделям данных, значит главная цель - именно построить модель для магазина, а не наполнить приложение всякими приколами....
> > 
> > 
> > Как вариант, может добавить рейтинг к товарам и просто сначала выводить товары с хорошим рейтингом Правда, возникает другой вопрос кто может ставить рейтинг. Очевидно, это не должен делать любой пользователь. Поэтому надо будет отслеживать покупал ли этот товар данный пользователь, если да, то может оценить, иначе нет.
> > Но это чисто мои мысли, но звучит прикольно
> 
> ну исходя из описания предметной области, у меня есть такая функция, как отзывы. Отзывы покупатель может сделать только на приобретенный товар (на вб и яндексе сейчас вроде как такая же функция). Как вариант в отзыве можно добавить возможность поставить рейтинг (0-5), а при отображении элементов сделать просто сортировку по рейтингу.

Ну вооот, тогда можно попробовать такое реализовать

**Comment by wldmr-key** [comment]
> а что тогда делать..... а если сделать как раз администратора (обозначить, что в самом начале 1 администратор магазина, но у него есть возможность создавать аккаунты для других администраторов), который как раз будет делать аккаунты для поставщиков? а проверять на сколько адекватный этот поставщик(там может какую-то документацию и тд), а также связываться с поставщиком администратор будет где-то в другом месте? Ну да, и следить за оборотом магазина

как вариант такой сценарий: поставщик авторизуется в системе, но начать работать в ней (в отличие от покупателя) он может тольок после подтверждения магазином (администратором)

**Comment by BazhinaJuliannaaa** [comment]
![Безымянный-1](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/f9bda600-cb77-4abb-a3dc-21d8b6a5ad9e)

**Comment by wldmr-key** [comment]
навскидку неплохо. Несколько фрустрируют три входа. А по логину ты не можешь определить, кто к тебе пришел?

**Comment by BazhinaJuliannaaa** [comment]
![Безымянный-1](https://github.com/BazhinaJuliannaaa/course_Bazhina/assets/133148928/a8c01036-75b8-4365-99a9-bedf320b786a)
могу
